/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as AppRouteImport } from './routes/app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTransacoesRouteImport } from './routes/app/transacoes'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppCategoriasRouteImport } from './routes/app/categorias'
import { Route as PublicRecuperarSenhaRouteImport } from './routes/_public/recuperar-senha'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicCriarContaRouteImport } from './routes/_public/criar-conta'
import { Route as PublicRecuperarSenhaTokenRouteImport } from './routes/_public/recuperar-senha/$token'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const PublicRecuperarSenhaRoute = PublicRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCriarContaRoute = PublicCriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecuperarSenhaTokenRoute =
  PublicRecuperarSenhaTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => PublicRecuperarSenhaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/ui': typeof UiRoute
  '/criar-conta': typeof PublicCriarContaRoute
  '/login': typeof PublicLoginRoute
  '/recuperar-senha': typeof PublicRecuperarSenhaRouteWithChildren
  '/app/categorias': typeof AppCategoriasRoute
  '/app/profile': typeof AppProfileRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/': typeof AppIndexRoute
  '/recuperar-senha/$token': typeof PublicRecuperarSenhaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ui': typeof UiRoute
  '/criar-conta': typeof PublicCriarContaRoute
  '/login': typeof PublicLoginRoute
  '/recuperar-senha': typeof PublicRecuperarSenhaRouteWithChildren
  '/app/categorias': typeof AppCategoriasRoute
  '/app/profile': typeof AppProfileRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app': typeof AppIndexRoute
  '/recuperar-senha/$token': typeof PublicRecuperarSenhaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/ui': typeof UiRoute
  '/_public/criar-conta': typeof PublicCriarContaRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/recuperar-senha': typeof PublicRecuperarSenhaRouteWithChildren
  '/app/categorias': typeof AppCategoriasRoute
  '/app/profile': typeof AppProfileRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/': typeof AppIndexRoute
  '/_public/recuperar-senha/$token': typeof PublicRecuperarSenhaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ui'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/app/categorias'
    | '/app/profile'
    | '/app/transacoes'
    | '/app/'
    | '/recuperar-senha/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ui'
    | '/criar-conta'
    | '/login'
    | '/recuperar-senha'
    | '/app/categorias'
    | '/app/profile'
    | '/app/transacoes'
    | '/app'
    | '/recuperar-senha/$token'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/app'
    | '/ui'
    | '/_public/criar-conta'
    | '/_public/login'
    | '/_public/recuperar-senha'
    | '/app/categorias'
    | '/app/profile'
    | '/app/transacoes'
    | '/app/'
    | '/_public/recuperar-senha/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/recuperar-senha': {
      id: '/_public/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof PublicRecuperarSenhaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/criar-conta': {
      id: '/_public/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof PublicCriarContaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/recuperar-senha/$token': {
      id: '/_public/recuperar-senha/$token'
      path: '/$token'
      fullPath: '/recuperar-senha/$token'
      preLoaderRoute: typeof PublicRecuperarSenhaTokenRouteImport
      parentRoute: typeof PublicRecuperarSenhaRoute
    }
  }
}

interface PublicRecuperarSenhaRouteChildren {
  PublicRecuperarSenhaTokenRoute: typeof PublicRecuperarSenhaTokenRoute
}

const PublicRecuperarSenhaRouteChildren: PublicRecuperarSenhaRouteChildren = {
  PublicRecuperarSenhaTokenRoute: PublicRecuperarSenhaTokenRoute,
}

const PublicRecuperarSenhaRouteWithChildren =
  PublicRecuperarSenhaRoute._addFileChildren(PublicRecuperarSenhaRouteChildren)

interface PublicRouteChildren {
  PublicCriarContaRoute: typeof PublicCriarContaRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRecuperarSenhaRoute: typeof PublicRecuperarSenhaRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCriarContaRoute: PublicCriarContaRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRecuperarSenhaRoute: PublicRecuperarSenhaRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppProfileRoute: AppProfileRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
